# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d076e6b12355416739c0c12344667e0e98fee8f9099277e182d85ba1ad84a1e0104d8846e1c3ec93eb88958829bfa3dcfbf414a56d19f1e9b46bf09389828f17

test:
  secret_key_base: 662e3821bd134d7c0ed7c27588a2f9d46943204725d7d7220b6e0c4544f4cf2e3a3b6de9595d6b14d501bea09db0bc324c515694c2f4b50c85e50cb2150ef8c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
